name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@v31
        with:
          install_url: https://releases.nixos.org/nix/nix-2.35.2/install
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Set Git credentials
        run: |
          git config --global 'url.https://api@github.com/'.insteadOf 'https://github.com/'
          git config --global 'url.https://ssh@github.com/'.insteadOf 'ssh://git@github.com/'
          git config --global 'url.https://git@github.com/'.insteadOf 'git@github.com:'
      - uses: cachix/cachix-action@v17
        with:
          name: veridise-public
          authToken: '${{ secrets.CACHIX_PUBLIC_TOKEN }}'
      - name: Build
        run: nix --print-build-logs flake check
