name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      # v37.1.0
      - uses: cachix/install-nix-action@d1ca217b388ee87b2507a9a93bf01368bde7cec2
        with:
          install_url: https://releases.nixos.org/nix/nix-2.23.3/install
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Set Git credentials
        run: |
          git config --global 'url.https://api@github.com/'.insteadOf 'https://github.com/'
          git config --global 'url.https://ssh@github.com/'.insteadOf 'ssh://git@github.com/'
          git config --global 'url.https://git@github.com/'.insteadOf 'git@github.com:'
      - uses: cachix/cachix-action@v17
        with:
          name: veridise-public
          authToken: '${{ secrets.CACHIX_PUBLIC_TOKEN }}'
      - name: Build
        run: nix --print-build-logs flake check
